DROP DATABASE IF EXISTS socialapp;
CREATE DATABASE socialapp;
use socialapp;


CREATE TABLE IF NOT EXISTS user(
    uID INT PRIMARY KEY UNIQUE NOT NULL,
    roleID INT NOT NULL,
    userEmail VARCHAR(20) NOT NULL, 
    userName VARCHAR(20) NOT NULL,
    sex VARCHAR(10) NOT NULL,
    birthDate DATE,
    firstName VARCHAR(20) NOT NULL,
    lastName VARCHAR(20) NOT NULL,
    createTime DATETIME,
    commentContent TEXT
);

CREATE TABLE IF NOT EXISTS userprofile(
    uID INT NOT NULL,

);

CREATE TABLE IF NOT EXISTS setting(
    sID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT NOT NULL,
    sound BIT NOT NULL DEFAULT 1,
    vibration BIT NOT NULL DEFAULT 0,
    feedback BIT NOT NULL DEFAULT 0,
    messages BIT NOT NULL DEFAULT 1,
    friendRequest BIT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS activity(
    aID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT NOT NULL,
    createTime DATETIME NOT NULL,
     actName VARCHAR(20) NOT NULL,
     actDescribe VARCHAR(500) NOT NULL,
     view INT DEFAULT 0,
     follow INT DEFAULT 0,
     star INT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS album(
    albumID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT NOT NULL,
    albumName VARCHAR(20) NOT NULL,
    length INT NOT NULL DEFAULT 0,
    follow INT NOT NULL DEFAULT 0,
    star INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS photo(
    pID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT NOT NULL,
    albumID INT NOT NULL,
    PName VARCHAR(20) NOT NULL,
    path VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS music(
    mID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT NOT NULL,
    mName VARCHAR(20) NOT NULL,
    time TIME,
    singer VARCHAR(20),
    lyric TEXT
);

CREATE TABLE IF NOT EXISTS video(
    vID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    uID INT NOT NULL,
    vName VARCHAR(20) NOT NULL,
    time TIME
);

CREATE TABLE IF NOT EXISTS feedback(
    fID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    targetID INT NOT NULL,
    createTime DATETIME
);

CREATE TABLE IF NOT EXISTS message(
    mID INT PRIMARY KEY UNIQUE NOT NULL,
    sourceID INT NOT NULL,
    targetID INT NOT NULL,
    createTime DATETIME,
    content BLOB
);

CREATE TABLE IF NOT EXISTS chat(
    cID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
    senderID INT NOT NULL,
    recieverID INT NOT NULL,
    sendTime DATETIME NOT NULL,
    sendContent VARCHAR(500) NOT NULL,
    remark VARCHAR(200)
);


CREATE TABLE IF NOT EXISTS friend(
    fID INT PRIMARY KEY UNIQUE NOT NULL,
    uID INT NOT NULL,
    nickName VARCHAR(20),
    comment VARCHAR(20)
);


-- CREATE TABLE IF NOT EXISTS group(
--     gID INT PRIMARY KEY UNIQUE NOT NULL,
--     uID INT NOT NULL,
--     createTime DATETIME,
--     gName VARCHAR(20) NOT NULL,
--     gDescribe TEXT
-- );




